[project]
name = "pdf-merger2"
version = "0.1.0"
description = "A webapp fro merging, compress pdf and also convert ppt to pdf"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fitz>=0.0.1.dev2",
    "flask>=3.1.0",
    "pymupdf>=1.25.5",
    "pywin32>=310",
]
